//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class All_Contragents_User
    {
        public string Login { get; set; }
        public string Name_Contragent { get; set; }
    }
}
