//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profi.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProfiDBEntities2 : DbContext
    {
        public ProfiDBEntities2()
            : base("name=ProfiDBEntities2")
        {
        }

        private static ProfiDBEntities2 _context;
        public static ProfiDBEntities2 GetContext()
        {
            if (_context == null)
                _context = new ProfiDBEntities2();
            return _context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contragent> Contragents { get; set; }
        public virtual DbSet<LogInJournal> LogInJournals { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Role_User> Role_User { get; set; }
        public virtual DbSet<SAE> SAEs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<All_Contragents_User> All_Contragents_User { get; set; }
        public virtual DbSet<ContragentSAE> ContragentSAEs { get; set; }
        public virtual DbSet<LogInUser> LogInUsers { get; set; }
        public virtual DbSet<PhotosSAE> PhotosSAEs { get; set; }
        public virtual DbSet<SAE_Categories> SAE_Categories { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
