//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotosSAE
    {
        public string Name_SAE { get; set; }
        public int Price { get; set; }
        public int Profi_Point { get; set; }
        public string Photo_Path { get; set; }
        public int Id_SAE { get; set; }
    }
}
