//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAE()
        {
            this.Contragents = new HashSet<Contragent>();
        }
    
        public int Id_SAE { get; set; }
        public string Name_SAE { get; set; }
        public string Material_Base { get; set; }
        public int Age { get; set; }
        public int Count { get; set; }
        public string Content { get; set; }
        public string Result { get; set; }
        public int Price { get; set; }
        public int Profi_Point { get; set; }
        public string Photo_Path { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contragent> Contragents { get; set; }
    }
}
