//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAE_Photo
    {
        public int Id_SAE { get; set; }
        public int Id_Photo { get; set; }
        public int Main_Photo { get; set; }
    
        public virtual Photo Photo { get; set; }
        public virtual SAE SAE { get; set; }
    }
}
